In [1]:
import pandas as pd

In [2]:
persones = pd.read_csv('./2018_accidents_persones_gu_bcn_.csv')
persones.head()
causes = pd.read_csv('./2018_accidents_causes_.csv')
gestionats = pd.read_csv('./2018_accidents_gu_bcn.csv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 18, saw 2

In [59]:
codi = accidents.loc[accidents['Coordenada_UTM_Y'] == ]
codi

,Codi_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Descripcio_tipus_vehicle,Descripcio_model,Descripcio_marca,Descripcio_color,Descripcio_carnet,Antiguitat_carnet,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S007344,1,Ciutat Vella,1,el Raval,269108,Rambla ...,1,Diumenge,Dg,...,Turisme,CORDOBA,SEAT,Blanc,B,5,431228.3,4581110.84,2.176455,41.376735
14917,2018S009862,1,Ciutat Vella,1,el Raval,269108,Rambla ...,5,Dimecres,Dc,...,Turisme,CORSA,OPEL,Verd,B,20,431228.3,4581110.84,2.176455,41.376735

In [16]:
accidents.head()

,Codi_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Descripcio_tipus_vehicle,Descripcio_model,Descripcio_marca,Descripcio_color,Descripcio_carnet,Antiguitat_carnet,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S007344,1,Ciutat Vella,1,el Raval,269108,Rambla ...,1,Diumenge,Dg,...,Turisme,CORDOBA,SEAT,Blanc,B,5,431228.30,4581110.84,2.176455,41.376735
1,2018S009617,1,Ciutat Vella,1,el Raval,701265,B-10 (Besòs) ...,K110,Dilluns,Dl,...,Turisme,206,PEUGEOT,Blau,B,1,431320.52,4580791.56,2.177594,41.373868
2,2018S008382,1,Ciutat Vella,2,el Barri Gòtic,34308,Ferran ...,2,Divendres,Dv,...,"Camió rígid > 3,5 tones",Desconegut,DAF-HERMANNS,Taronja,C,25,431052.34,4581514.69,2.174305,41.380358
3,2018S002684,1,Ciutat Vella,2,el Barri Gòtic,55909,Call ...,21,Dilluns,Dl,...,"Camió rígid > 3,5 tones",ML140E24 E,IVECO FIAT,Blanc,C,11,431241.33,4581757.56,2.176538,41.382561
4,2018S004886,1,Ciutat Vella,2,el Barri Gòtic,82901,Colom ...,25,Dimarts,Dm,...,Taxi,TOLEDO,SEAT,Negre/Groc,B,5,431390.44,4581135.49,2.178391,41.376971

In [49]:
accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19079 entries, 0 to 19078
Data columns (total 28 columns):
Codi_expedient              19079 non-null object
Codi_districte              19079 non-null int64
Nom_districte               19079 non-null object
Codi_barri                  19079 non-null int64
Nom_barri                   19079 non-null object
Codi_carrer                 19079 non-null int64
Nom_carrer                  19079 non-null object
Num_postal                  5144 non-null object
Descripcio_dia_setmana      19079 non-null object
Dia_setmana                 19079 non-null object
Descripcio_tipus_dia        19079 non-null object
Any                         19079 non-null int64
Mes_any                     19079 non-null int64
Nom_mes                     19079 non-null object
Dia_mes                     19079 non-null int64
Hora_dia                    19079 non-null int64
Descripcio_torn             19079 non-null object
Descripcio_causa_vianant    19079 non-null object
Descripcio_tipus_vehicle    19079 non-null object
Descripcio_model            19079 non-null object
Descripcio_marca            19079 non-null object
Descripcio_color            19079 non-null object
Descripcio_carnet           19079 non-null object
Antiguitat_carnet           19079 non-null object
Coordenada_UTM_X            19079 non-null float64
Coordenada_UTM_Y            19079 non-null float64
Longitud                    19079 non-null float64
Latitud                     19079 non-null float64
dtypes: float64(4), int64(7), object(17)
memory usage: 4.1+ MB

In [66]:
causes.head()

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Mes_any,Nom_mes,Dia_mes,Hora_dia,Descripcio_torn,Descripcio_causa_mediata,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S009653,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",700059,Vallvidrera a les Planes ...,102-112,Dimarts,Dm,...,12,Desembre,18,6,Matí,Alcoholèmia,424026.58,4586957.76,2.089608,41.428747
1,2018S000730,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",73139,Vimetera / Gespa ...,NaN,Dissabte,Ds,...,1,Gener,27,10,Matí,No hi ha causa mediata,424044.33,4586368.63,2.089894,41.423443
2,2018S009722,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",700059,Vallvidrera a les Planes ...,K63,Dijous,Dj,...,12,Desembre,20,4,Nit,Alcoholèmia,424125.69,4586916.42,2.090799,41.428384
3,2018S004776,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",700059,Vallvidrera a les Planes ...,58-96,Dijous,Dj,...,6,Juny,21,15,Tarda,No hi ha causa mediata,424200.01,4586750.40,2.091709,41.426896
4,2018S007190,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",700059,Vallvidrera a les Planes ...,K57,Dimarts,Dm,...,9,Setembre,25,10,Matí,No hi ha causa mediata,424382.52,4586337.05,2.093945,41.423190

In [67]:
gestionats.head()

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Descripcio_causa_vianant,Numero_morts,Numero_lesionats_lleus,Numero_lesionats_greus,Numero_victimes,Numero_vehicles_implicats,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S000150,3,Sants-Montjuïc,12,la Marina del Prat Vermell,701819,Número 3 Zona Franca / E Zona Franca ...,69-75,Dilluns,Dl,...,No és causa del vianant,0,1,0,1,2,427265.97,4576644.81,2.129612,41.336163
1,2018S000761,3,Sants-Montjuïc,11,el Poble-sec,234001,Olímpic ...,5-7,Diumenge,Dg,...,No és causa del vianant,0,0,0,0,2,429210.58,4579530.49,2.152513,41.362326
2,2018S005151,3,Sants-Montjuïc,12,la Marina del Prat Vermell,370531,A Zona Franca / Número 6 Zona Franca ...,NaN,Dimecres,Dc,...,No és causa del vianant,0,1,0,1,2,427519.99,4575229.36,2.132817,41.323437
3,2018S000933,3,Sants-Montjuïc,12,la Marina del Prat Vermell,701819,Número 3 Zona Franca / E ...,69-75,Diumenge,Dg,...,No és causa del vianant,0,2,0,2,1,427360.59,4576569.22,2.130752,41.335490
4,2018S006926,3,Sants-Montjuïc,12,la Marina del Prat Vermell,370203,Número 3 Zona Franca ...,77-111,Divendres,Dv,...,No és causa del vianant,0,0,0,0,2,426842.33,4576816.19,2.124529,41.337668