In [1]:
import pandas as pd
import numpy as np

## Read the files

In [2]:
persones_17 = pd.read_excel('../2017_accidents_persones_gu_bcn_.xlsx')
persones_18 = pd.read_excel('../2018_accidents_persones_gu_bcn_.xlsx')
persones_18.head()

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Desc_Tipus_vehicle_implicat,Descripcio_sexe,Edat,Descripcio_tipus_persona,Descripcio_situacio,Descripcio_victimitzacio,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud
0,2018S000001,3,Sants-Montjuïc,11,el Poble-sec,273400,Paral·lel ...,117-119,Dilluns,Dl,...,Turisme,Home,41,Conductor,Presentat,Ferit lleu: Amb assistència sanitària en lloc ...,429910.63,4580909.28,2160723.0,41374806
1,2018S000001,3,Sants-Montjuïc,11,el Poble-sec,273400,Paral·lel ...,NaN,Dilluns,Dl,...,Turisme,Home,54,Conductor,Presentat,Ferit lleu: Amb assistència sanitària en lloc ...,429910.63,4580909.28,2160723.0,41374806
2,2018S000002,2,Eixample,9,la Nova Esquerra de l'Eixample,361406,Viladomat / Rosselló ...,NaN,Dilluns,Dl,...,Ciclomotor,Home,45,Conductor,Presentat,Ferit lleu: Hospitalització fins a 24h,428882.97,4582216.76,2148281.0,41386492
3,2018S000003,10,Sant Martí,64,el Camp de l'Arpa del Clot,161407,Indústria ...,252,Dilluns,Dl,...,Motocicleta,Home,70,Conductor,Presentat,Ferit lleu: Hospitalització fins a 24h,431447.19,4585099.12,2178621.0,41412675
4,2018S000005,8,Nou Barris,56,Vallbona,330606,C-17 (Barcelona) ...,K14,Dilluns,Dl,...,Turisme,Dona,33,Conductor,Presentat,Ferit lleu: Hospitalització fins a 24h,431568.59,4590758.85,2179432.0,41463661

In [3]:
persones_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11854 entries, 0 to 11853
Data columns (total 28 columns):
Numero_expedient               11854 non-null object
Codi_districte                 11854 non-null int64
Nom_districte                  11854 non-null object
Codi_barri                     11854 non-null int64
Nom_barri                      11854 non-null object
Codi_carrer                    11854 non-null int64
Nom_carrer                     11854 non-null object
Num_postal                     4607 non-null object
Descripcio_dia_setmana         11854 non-null object
Dia_setmana                    11854 non-null object
Descripcio_tipus_dia           11854 non-null object
Any                            11854 non-null int64
Mes_ any                       11854 non-null int64
Nom_mes                        11854 non-null object
Dia_mes                        11854 non-null int64
Descripcio_torn                11854 non-null object
Hora_dia                       11854 non-null int64
Descripcio_causa_vianant       11854 non-null object
Desc_Tipus_vehicle_implicat    11854 non-null object
Descripcio_sexe                11854 non-null object
Edat                           11854 non-null object
Descripcio_tipus_persona       11854 non-null object
Descripcio_situacio            11854 non-null object
Descripcio_victimitzacio       11854 non-null object
Coordenada_UTM_X               11854 non-null float64
Coordenada_UTM_Y               11854 non-null float64
Longitud                       11854 non-null float64
Latitud                        11854 non-null int64
dtypes: float64(3), int64(8), object(17)
memory usage: 2.5+ MB

## Append one year to another

In [4]:
persones = pd.concat([persones_17, persones_18], ignore_index=True)

In [5]:
persones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24002 entries, 0 to 24001
Data columns (total 28 columns):
Numero_expedient               24002 non-null object
Codi_districte                 24002 non-null int64
Nom_districte                  24002 non-null object
Codi_barri                     24002 non-null int64
Nom_barri                      24002 non-null object
Codi_carrer                    24002 non-null int64
Nom_carrer                     23991 non-null object
Num_postal                     16734 non-null object
Descripcio_dia_setmana         24002 non-null object
Dia_setmana                    24002 non-null object
Descripcio_tipus_dia           24002 non-null object
Any                            24002 non-null int64
Mes_ any                       24002 non-null int64
Nom_mes                        24002 non-null object
Dia_mes                        24002 non-null int64
Descripcio_torn                24002 non-null object
Hora_dia                       24002 non-null int64
Descripcio_causa_vianant       24002 non-null object
Desc_Tipus_vehicle_implicat    24002 non-null object
Descripcio_sexe                24002 non-null object
Edat                           24002 non-null object
Descripcio_tipus_persona       24002 non-null object
Descripcio_situacio            24002 non-null object
Descripcio_victimitzacio       24002 non-null object
Coordenada_UTM_X               23985 non-null float64
Coordenada_UTM_Y               23985 non-null float64
Longitud                       24002 non-null object
Latitud                        24002 non-null object
dtypes: float64(2), int64(7), object(19)
memory usage: 5.1+ MB

## We change the name of the DataFrame, drop the unnecessary columns and change some of the names.

In [6]:
crashes = persones

In [7]:
cols=[1,3,4,5,6,7,9,22,24,25,26,27]
crashes.drop(crashes.columns[cols], axis=1, inplace=True)

In [8]:
crashes.rename(columns={"Descripcio_dia_setmana": "Dia_setmana", "Descripcio_tipus_dia": "Tipus_dia", "Mes_ any": "Mes", "Descripcio_torn": "Torn", "Hora_dia": "Hora", "Descripcio_causa_vianant": "Causa", "Desc_Tipus_vehicle_implicat":"Vehicle_implicat","Descripcio_sexe":"Sexe", "Descripcio_tipus_persona":"Persona_afectada", "Descripcio_victimitzacio": "Victima"}, inplace=True)
crashes.head()

,Numero_expedient,Nom_districte,Dia_setmana,Tipus_dia,Any,Mes,Nom_mes,Dia_mes,Torn,Hora,Causa,Vehicle_implicat,Sexe,Edat,Persona_afectada,Victima
0,2017S000001,Sarrià-Sant Gervasi,Diumenge,Laboral,2017,1,Gener,1,Nit,4,No és causa del vianant,Turismo,Home,50,Conductor,Ferit lleu
1,2017S000002,Eixample,Diumenge,Laboral,2017,1,Gener,1,Nit,2,No és causa del vianant,Motocicleta,Home,47,Conductor,Ferit lleu
2,2017S000004,Eixample,Diumenge,Laboral,2017,1,Gener,1,Matí,7,No és causa del vianant,Motocicleta,Dona,27,Conductor,Ferit lleu
3,2017S000005,Sant Martí,Diumenge,Laboral,2017,1,Gener,1,Matí,7,No és causa del vianant,Ciclomotor,Dona,40,Passatger,Ferit lleu
4,2017S000005,Sant Martí,Diumenge,Laboral,2017,1,Gener,1,Matí,7,No és causa del vianant,Ciclomotor,Home,37,Conductor,Ferit lleu

### In order to be able to use the 'Edat' column as a calculation, we turn the column into an integer and force the non convertible values into Nan.

In [9]:
crashes['Edat'] = pd.to_numeric(crashes.Edat, errors='coerce')
crashes.Edat.unique()

array([ 50.,  47.,  27.,  40.,  37.,  61.,  31.,  35.,  91.,  29.,  23.,
        26.,  57.,  18.,  49.,  77.,  15.,  25.,  54.,  51.,  22.,  33.,
        69.,  30.,  70.,  34.,  38.,  55.,  65.,  45.,  36.,  17.,  43.,
        20.,  62.,  32.,  24.,  52.,  10.,   6.,  46.,  19.,  21.,  42.,
        76.,  83.,  79.,  39.,  44.,  28.,  89.,  56.,  59.,  58.,  80.,
        16.,  41.,  84.,  66.,  nan,  67.,  87.,  12.,  64.,  85.,  60.,
        48.,  75.,  74.,  53.,   9.,  88.,  81.,  72.,   0.,  11.,  92.,
        63.,   5.,   1.,   2.,  78.,  71.,  86.,  73.,   7.,  68.,  13.,
         3.,  14.,   8.,  82.,   4.,  98.,  90.,  94., 117.,  97.,  96.,
        95.,  93.])

In [10]:
crashes.Edat.dtype

dtype('float64')

In [11]:
crashes.Any = crashes.Any.apply(str)

In [12]:
crashes["Dia_mes"] = crashes["Dia_mes"].map("{:02}".format)
crashes["Mes"] = crashes["Mes"].map("{:02}".format)

In [13]:
crashes['Data'] = crashes.apply(lambda row: row.Any + '-' + row.Mes + '-' + row.Dia_mes, axis = 1)
crashes.head()

,Numero_expedient,Nom_districte,Dia_setmana,Tipus_dia,Any,Mes,Nom_mes,Dia_mes,Torn,Hora,Causa,Vehicle_implicat,Sexe,Edat,Persona_afectada,Victima,Data
0,2017S000001,Sarrià-Sant Gervasi,Diumenge,Laboral,2017,01,Gener,01,Nit,4,No és causa del vianant,Turismo,Home,50.0,Conductor,Ferit lleu,2017-01-01
1,2017S000002,Eixample,Diumenge,Laboral,2017,01,Gener,01,Nit,2,No és causa del vianant,Motocicleta,Home,47.0,Conductor,Ferit lleu,2017-01-01
2,2017S000004,Eixample,Diumenge,Laboral,2017,01,Gener,01,Matí,7,No és causa del vianant,Motocicleta,Dona,27.0,Conductor,Ferit lleu,2017-01-01
3,2017S000005,Sant Martí,Diumenge,Laboral,2017,01,Gener,01,Matí,7,No és causa del vianant,Ciclomotor,Dona,40.0,Passatger,Ferit lleu,2017-01-01
4,2017S000005,Sant Martí,Diumenge,Laboral,2017,01,Gener,01,Matí,7,No és causa del vianant,Ciclomotor,Home,37.0,Conductor,Ferit lleu,2017-01-01

In [14]:
crashes.Data = crashes.Data.astype('datetime64[ns]')

In [15]:
crashes.to_csv('accidents.csv')